services:
  omarchy-zellij-theme-docs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: omarchy-zellij-theme-docs
    restart: unless-stopped
    networks:
      - caddy_net
    labels:
      caddy: omarchy-zellij-theme.reposito.rio.br
      caddy.reverse_proxy: "{{upstreams 3011}}"
      caddy.encode: "gzip"
    expose:
      - 3011

networks:
  caddy_net:
    external: true
