services:
  mugdoc-docs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mugdoc-docs
    restart: unless-stopped
    networks:
      - caddy_net
    labels:
      caddy: mugdoc.reposito.rio.br
      caddy.reverse_proxy: "{{upstreams 3010}}"
      caddy.encode: "gzip"
    expose:
      - 3010

networks:
  caddy_net:
    external: true
